name: nz_fabrics
description: "NZ utility management system."

publish_to: 'none'

version: 1.0.5

environment:
  sdk: 3.7.0-323.0.dev


# - - - - - - - - - - PACKAGES START - - - - - - - - - - #
dependencies:
  flutter:
    sdk: flutter

  #------------- Stage Management ----------------
  get: ^4.7.2
  #------------- Utility Packages-----------------
  http: ^1.3.0
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  reorderable_grid_view: ^2.2.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  zoom_widget: ^2.0.1
  modal_bottom_sheet: ^3.0.0
  web_socket_channel: ^3.0.3
  badges: ^3.1.2
  flutter_local_notifications: ^17.2.4
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  hexcolor: ^3.0.1
  upgrader: ^11.3.1
  photo_view: ^0.15.0
  zoom_pinch_overlay: ^1.4.3
  in_app_update: ^4.2.2
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0

  #----------------- download package --------------------
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  syncfusion_flutter_xlsio: ^29.1.38
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  excel: ^4.0.6
  file_picker: ^10.1.2
  share_plus: ^10.1.4


  #----------------- Chart --------------------
  syncfusion_flutter_charts: ^29.1.38
  syncfusion_flutter_gauges: ^29.1.38
  syncfusion_flutter_datagrid: ^29.1.38
  flutter_expandable_table: ^2.1.0

  #----------------- Animation--------------------
  lottie: ^3.3.0
  animations: ^2.0.11
  animated_text_kit: ^4.2.2
  dropdown_search: ^6.0.2
  searchfield: ^1.2.7

  # - - - - - - - - - - PACKAGES END - - - - - - - - - - #
  cupertino_icons: ^1.0.8
  syncfusion_flutter_core: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/new_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/new_logo.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true

  # - - - - - - - - LOCAL ASSETS - - - - - - - - #
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie_animation/


  # - - - - - - - - LOCAL FONTS - - - - - - - - #
  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600

    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700