name: nz_fabrics
description: "NZ utility management system."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


# - - - - - - - - - - PACKAGES START - - - - - - - - - - #
dependencies:
  flutter:
    sdk: flutter

  #------------- Stage Management ----------------
  get: ^4.7.2
  #------------- Utility Packages-----------------
  http: ^1.3.0
  flutter_svg: ^2.1.0
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  double_back_to_close: ^2.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  reorderable_grid_view: ^2.2.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0
  zoom_widget: ^2.0.1
  modal_bottom_sheet: ^3.0.0
  web_socket_channel: ^3.0.1
  badges: ^3.1.2
  flutter_local_notifications: ^17.2.4
  loader_overlay: ^4.0.3
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  hexcolor: ^3.0.1
  upgrader: ^11.3.1
  photo_view: ^0.15.0
  zoom_pinch_overlay: ^1.4.3

  #----------------- download package --------------------
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.1
  syncfusion_flutter_xlsio: ^29.1.38
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  excel: ^3.0.0
  file_picker: ^8.1.3
  share_plus: ^7.2.1


  #----------------- Chart --------------------
  syncfusion_flutter_charts: ^29.1.38
  syncfusion_flutter_gauges: ^29.1.38
  syncfusion_flutter_datagrid: ^29.1.38
  flutter_expandable_table: ^2.1.0

  #----------------- Animation--------------------
  lottie: ^3.1.2
  animations: ^2.0.11
  animated_text_kit: ^4.2.2
  dropdown_search: ^6.0.1
  searchfield: ^1.1.6

  # - - - - - - - - - - PACKAGES END - - - - - - - - - - #
  cupertino_icons: ^1.0.8
  syncfusion_flutter_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # - - - - - - - - LOCAL ASSETS - - - - - - - - #
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie_animation/


  # - - - - - - - - LOCAL FONTS - - - - - - - - #
  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600

    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700